[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
sources = ["RRAEs"]

[project]
name = "RRAEs"
version = "0.1"
dependencies = ["jax", "jaxlib", "matplotlib", "numpy", "equinox", "optax", "numpy", "pandas", "torchvision", "jaxtyping"]
