[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "RRAEs"
version = "0.1"
dependencies = ["pytest", "dill", "jax", "jaxlib", "matplotlib", "numpy", "equinox", "optax", "numpy", "pandas", "torchvision", "jaxtyping", "PyQt5"]
